# https://sap.github.io/jenkins-library/
general:
  gitSshKeyCredentialsId: 'GITHUBALUNDESAP'
  collectTelemetryData: false
steps:
  setupCommonPipelineEnvironment:
    collectTelemetryData: true
  mtaBuild:
    buildTarget: 'CF'
    mtaBuildTool: 'cloudMbt'
    platform: 'cf'
    defaultNpmRegistry: 'https://registry.npmjs.org/'
    cloudMbt:
      dockerImage: 'alunde/mbtci:latest'
    dockerBasedModules: ['conciletime-cli']
    postBuildAction: 'mbt --version'
  # https://github.wdf.sap.corp/pages/ContinuousDelivery/piper-doc/steps/cloudFoundryDeploy/
  cloudFoundryDeploy:
    verbose: false
    deployTool: 'mtaDeployPlugin'
    #deployTool: 'cf_native'
    deployType: 'standard'
    cloudFoundry:
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
      org: 'ConcileTime'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
      dockerImage: 'ppiper/cf-cli'
      #dockerImage: 'alunde/cf-cli-ci'
      dockerWorkspace: '/home/jenkins/piper'
      #https://docs.pivotal.io/pivotalcf/2-6/devguide/deploy-apps/large-app-deploy.html
      #CF_STAGING_TIMEOUT: 15
      #CF_STARTUP_TIMEOUT: 5
    mtaDeployParameters: '-t 9000 -f -e mta_to_cf-dev.mtaext'
    postDeployAction: "cf map-route concile_web_v0 conciletime.com --hostname '*' ; cf bs concile_utl_v0 CONCILE_REG ; cf restage concile_utl_v0 ; cf --version"
  xsaDeploy:
    XSA:
      apiEndpoint: 'https://api.parvus.lcfx.net'
      org: 'lcfx'
      space: 'DEV'
      credentialsId: 'CF_CREDENTIALSID'
  mailSendNotifiction:
    notificationAttachment: true
    notificationRecipients: 'andrew.lunde@sap.com'
    notifyCulprits: false
  slackSendNotification:
    credentialsId: 'SLACKSECRET'
    channel: '#jenkins_builds'
